mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 1 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 2 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 3 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 4 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 5 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 6 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 7 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 9 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 10 --lengthbound 3.5

mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 1 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 2 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 3 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 4 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 5 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 6 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 7 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 8 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 9 --lengthbound 3.5
mpirun -n 8 ./main.py QH --stage1 --stage2 --single_stage --max_modes 3 --ncoils 10 --lengthbound 3.5
